# Generated by Django 3.2.25 on 2024-04-13 15:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0004_alter_stock_quantity'),
        ('bulls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pull',
            new_name='Bull',
        ),
    ]
