# Generated by Django 3.2.25 on 2024-04-13 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stock_quantity'),
        ('bulls', '0002_rename_pull_bull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bull',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulls', to='stocks.stock'),
        ),
    ]
