# Generated by Django 4.2.11 on 2024-05-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earning',
            options={'ordering': ['-earning_date']},
        ),
    ]
