# Generated by Django 4.2.11 on 2024-05-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0002_alter_earning_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earning',
            options={'ordering': ['-created_at']},
        ),
    ]
