# Generated by Django 3.2.25 on 2024-04-10 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('symbol', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=100)),
                ('sector', models.CharField(choices=[('', '---------'), ('information technology', 'Information Technology'), ('health', 'Health Care'), ('financials', 'Financials'), ('consumer discretionary', 'Consumer Discretionary'), ('communication services', 'Communication Services'), ('industrials', 'Industrials'), ('consumer staples', 'Consumer Staples'), ('energy', 'Energy'), ('utilities', 'Utilities'), ('real estate', 'Real Estate'), ('materials', 'Materials')], default='', max_length=30)),
                ('order', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], default='hold', max_length=10)),
                ('order_date', models.DateField(blank=True)),
                ('order_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(blank=True)),
                ('content', models.TextField()),
                ('chart', models.ImageField(blank=True, upload_to='images/')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
