# Generated by Django 4.2.11 on 2024-04-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='chart',
        ),
        migrations.AlterField(
            model_name='stock',
            name='order',
            field=models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], default='hold', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, choices=[('', '---------'), ('information technology', 'Information Technology'), ('health', 'Health Care'), ('financials', 'Financials'), ('consumer discretionary', 'Consumer Discretionary'), ('communication services', 'Communication Services'), ('industrials', 'Industrials'), ('consumer staples', 'Consumer Staples'), ('energy', 'Energy'), ('utilities', 'Utilities'), ('real estate', 'Real Estate'), ('materials', 'Materials')], default='', max_length=30),
        ),
    ]
